make api docs generation conditional

diff --git a/_web/Makefile b/_web/Makefile
--- a/_web/Makefile
+++ b/_web/Makefile
@@ -1,13 +1,27 @@
-.PHONY: prod debug apidoc prep clean
-prod : clean deps apidoc
+.PHONY: summary prod debug apidoc prep clean
+
+APIDOC ?= yes
+
+prod : summary clean deps apidoc
+ifndef SITE_URL
+	echo "Error: Site URL not set. Production builds will not work without site url being set to generate a sitemap. Set with SITE_URL=[url]"
+	exit 1
+endif
 	grunt --siteurl=$(SITE_URL)
 
-debug: clean prep
+debug: summary clean prep apidoc
 	grunt serve
 
+summary:
+ifeq ($(APIDOC),no)
+	echo "API Documentation: disabled (API docs will not be included in the build. Only use this if you are generating the site for testing purposes.)"
+endif
+
 apidoc:
+ifeq ($(APIDOC),yes)
 	make -C apidoc
 	cp -r apidoc/build/apidoc extgen
+endif
 
 deps :
 	virtualenv .pythonenv
@@ -15,5 +29,6 @@ deps :
 	npm install
 	bower install
 
-clean : 
-	rm -r extgen/*
+clean :
+	rm -r extgen
+	mkdir extgen
